//! SRP-6a client math for HAP pair-setup.
//!
//! HomeKit's `pair-setup` uses SRP-6a over the 3072-bit group with SHA-512 as
//! the hash. This module holds the pure computation so it can be tested against
//! an independent implementation of the server side; `hap_pairing` keeps the
//! I/O and TLV8 framing.
//!
//! Notation follows RFC 5054:
//!
//! ```text
//! x  = H(s | H(I | ":" | P))
//! A  = g^a mod N
//! u  = H(PAD(A) | PAD(B))
//! k  = H(N | PAD(g))
//! S  = (B - k * g^x) ^ (a + u * x) mod N
//! K  = H(S)
//! M1 = H(H(N) XOR H(g) | H(I) | s | A | B | K)
//! M2 = H(A | M1 | K)
//! ```

use num_bigint::BigUint;
use sha2::{Digest, Sha512};

/// SRP-6a group modulus `N` — the 3072-bit group, as adopted by RFC 5054
/// appendix A from RFC 3526 group 15.
///
/// This value is not hand-copied. It is generated by RFC 3526's formula
///
/// ```text
/// N = 2^3072 - 2^3008 - 1 + 2^64 * ( floor(2^2942 * pi) + 1690314 )
/// ```
///
/// and `srp_group_matches_rfc3526_formula` in this module's tests re-derives it
/// from that formula at test time, so a corrupted digit cannot pass CI. The
/// other tests confirm the properties SRP depends on: 3072 bits, prime,
/// `(N-1)/2` prime, and `g = 5` a generator of the full group.
///
/// A previous revision of this file carried a value that was 3088 bits, not
/// equal to the RFC group, and composite — which is why the tests below are
/// deliberately paranoid rather than a formality.
pub const SRP_N_HEX: &str = "\
FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74\
020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F1437\
4FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED\
EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3DC2007CB8A163BF05\
98DA48361C55D39A69163FA8FD24CF5F83655D23DCA3AD961C62F356208552BB\
9ED529077096966D670C354E4ABC9804F1746C08CA18217C32905E462E36CE3B\
E39E772C180E86039B2783A2EC07A28FB5C55DF06F4C52C9DE2BCBF695581718\
3995497CEA956AE515D2261898FA051015728E5A8AAAC42DAD33170D04507A33\
A85521ABDF1CBA64ECFB850458DBEF0A8AEA71575D060C7DB3970F85A6E1E4C7\
ABF5AE8CDB0933D71E8C94E04A25619DCEE3D2261AD2EE6BF12FFA06D98A0864\
D87602733EC86A64521F2B18177B200CBBE117577A615D6C770988C0BAD946E2\
08E24FA074E5AB3143DB5BFCE0FD108E4B82D120A93AD2CAFFFFFFFFFFFFFFFF";

/// SRP-6a generator `g` for the 3072-bit group. RFC 5054 appendix A specifies
/// 5 for this group (RFC 3526 itself uses 2; SRP needs a full-group generator,
/// and 5 is a quadratic non-residue mod N whereas 2 is not).
pub const SRP_G: u32 = 5;

/// Length of the SRP private exponent `a`, in bytes. RFC 5054 section 3.1 asks
/// for at least 256 bits.
const PRIVATE_KEY_BYTES: usize = 32;

/// The client-side outputs of SRP-6a needed to drive M3 and check M4.
pub struct ClientSession {
    /// `A`, padded to the length of `N`, as sent in M3.
    pub public_a: Vec<u8>,
    /// `M1`, the client proof sent in M3.
    pub m1: Vec<u8>,
    /// `K`, the session key that later HKDF derivations are keyed on.
    pub session_key: Vec<u8>,
    /// `M2`, the server proof we expect to receive in M4.
    pub expected_m2: Vec<u8>,
}

/// Returns the group modulus `N`.
///
/// Panics only if [`SRP_N_HEX`] is not valid hex, which the tests rule out.
pub fn group_n() -> BigUint {
    BigUint::parse_bytes(SRP_N_HEX.as_bytes(), 16).expect("SRP_N_HEX is a valid hex constant")
}

/// Generates a fresh SRP private exponent `a`.
pub fn random_private_key() -> BigUint {
    let mut bytes = [0u8; PRIVATE_KEY_BYTES];
    use rand::RngCore;
    rand::thread_rng().fill_bytes(&mut bytes);
    BigUint::from_bytes_be(&bytes)
}

/// Runs the client half of SRP-6a.
///
/// `server_public` is `B` from M2 and `salt` is `s`. `a` is the client private
/// exponent, taken as a parameter rather than generated internally so tests can
/// pin it and get a reproducible exchange.
///
/// Rejects the two values RFC 5054 section 2.5.3 requires a client to abort on:
/// `B mod N == 0`, and `u == 0`. Both indicate a broken or hostile server, and
/// continuing would derive a session key an attacker can predict.
pub fn client_compute(
    username: &str,
    password: &str,
    salt: &[u8],
    server_public: &[u8],
    a: &BigUint,
) -> anyhow::Result<ClientSession> {
    let n = group_n();
    let g = BigUint::from(SRP_G);

    let big_b = BigUint::from_bytes_be(server_public);
    if (&big_b % &n).is_zero_value() {
        anyhow::bail!("SRP: server public key B is congruent to 0 mod N; aborting");
    }

    let big_a = g.modpow(a, &n);
    let a_padded = pad_to_n(&big_a, &n);
    let b_padded = pad_to_n(&big_b, &n);

    // u = H(PAD(A) | PAD(B))
    let u = {
        let mut h = Sha512::new();
        h.update(&a_padded);
        h.update(&b_padded);
        BigUint::from_bytes_be(&h.finalize())
    };
    if u.is_zero_value() {
        anyhow::bail!("SRP: u is zero; aborting");
    }

    // x = H(s | H(I | ":" | P))
    let x = {
        let inner = {
            let mut h = Sha512::new();
            h.update(username.as_bytes());
            h.update(b":");
            h.update(password.as_bytes());
            h.finalize()
        };
        let mut h = Sha512::new();
        h.update(salt);
        h.update(inner);
        BigUint::from_bytes_be(&h.finalize())
    };

    // k = H(N | PAD(g))
    let k = {
        let mut h = Sha512::new();
        h.update(n.to_bytes_be());
        h.update(pad_to_n(&g, &n));
        BigUint::from_bytes_be(&h.finalize())
    };

    // S = (B - k * g^x) ^ (a + u * x) mod N, with the subtraction taken mod N.
    let gx = g.modpow(&x, &n);
    let kgx = (&k * &gx) % &n;
    let base = (&big_b + &n - &kgx) % &n;
    let exp = a + &u * &x;
    let big_s = base.modpow(&exp, &n);

    // K = H(S)
    let session_key = {
        let mut h = Sha512::new();
        h.update(pad_to_n(&big_s, &n));
        h.finalize().to_vec()
    };

    // M1 = H(H(N) XOR H(g) | H(I) | s | A | B | K)
    //
    // `H(g)` is taken over g's *minimal* big-endian encoding — a single 0x05
    // byte — not over PAD(g). This differs from `k` above, which RFC 5054
    // explicitly defines as H(N | PAD(g)); the proof has no such padding rule
    // and Apple's receivers do not apply one.
    //
    // Padding it here was why pair-setup failed at M4 with HAP error 2
    // (authentication) against real hardware, even though every value in the
    // exchange was otherwise correct. A client/server round-trip cannot catch
    // this: both halves agree on the same wrong digest and the test passes.
    // Verified against a Mac running AirTunes/950.7.1 — minimal encoding
    // completes pair-setup, PAD(g) is rejected.
    let m1 = {
        let hash_n = Sha512::digest(n.to_bytes_be());
        let hash_g = Sha512::digest(g.to_bytes_be());
        let hash_xor: Vec<u8> = hash_n
            .iter()
            .zip(hash_g.iter())
            .map(|(l, r)| l ^ r)
            .collect();

        let mut h = Sha512::new();
        h.update(&hash_xor);
        h.update(Sha512::digest(username.as_bytes()));
        h.update(salt);
        h.update(&a_padded);
        h.update(&b_padded);
        h.update(&session_key);
        h.finalize().to_vec()
    };

    // M2 = H(A | M1 | K)
    let expected_m2 = {
        let mut h = Sha512::new();
        h.update(&a_padded);
        h.update(&m1);
        h.update(&session_key);
        h.finalize().to_vec()
    };

    Ok(ClientSession {
        public_a: a_padded,
        m1,
        session_key,
        expected_m2,
    })
}

/// Left-pads `value` with zeros to the byte length of `N`, per RFC 5054's PAD().
pub fn pad_to_n(value: &BigUint, n: &BigUint) -> Vec<u8> {
    let n_len = n.to_bytes_be().len();
    let bytes = value.to_bytes_be();
    if bytes.len() >= n_len {
        bytes
    } else {
        let mut padded = vec![0u8; n_len - bytes.len()];
        padded.extend_from_slice(&bytes);
        padded
    }
}

/// `BigUint::is_zero` lives behind the `num_traits::Zero` trait; this avoids
/// pulling that import in just for two checks.
trait IsZero {
    fn is_zero_value(&self) -> bool;
}

impl IsZero for BigUint {
    fn is_zero_value(&self) -> bool {
        self.to_bytes_be() == [0]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn n() -> BigUint {
        group_n()
    }

    /// Miller-Rabin. Deterministic enough for a constant that never changes.
    fn is_probable_prime(n: &BigUint) -> bool {
        let one = BigUint::from(1u32);
        let two = BigUint::from(2u32);
        let n_minus_1 = n - &one;

        let mut d = n_minus_1.clone();
        let mut r = 0u32;
        while (&d % &two) == BigUint::from(0u32) {
            d /= &two;
            r += 1;
        }

        for base in [2u32, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37] {
            let a = BigUint::from(base);
            let mut x = a.modpow(&d, n);
            if x == one || x == n_minus_1 {
                continue;
            }
            let mut witness = true;
            for _ in 0..r - 1 {
                x = x.modpow(&two, n);
                if x == n_minus_1 {
                    witness = false;
                    break;
                }
            }
            if witness {
                return false;
            }
        }
        true
    }

    #[test]
    fn srp_group_is_3072_bits() {
        assert_eq!(SRP_N_HEX.len(), 768, "N must be 768 hex digits");
        assert_eq!(n().bits(), 3072, "N must be exactly 3072 bits");
    }

    #[test]
    fn srp_group_is_prime() {
        assert!(is_probable_prime(&n()), "N must be prime");
    }

    #[test]
    fn srp_group_is_a_safe_prime() {
        let q = (n() - BigUint::from(1u32)) / BigUint::from(2u32);
        assert!(is_probable_prime(&q), "(N-1)/2 must be prime");
    }

    #[test]
    fn generator_5_generates_the_full_group() {
        // For a safe prime N = 2q+1, g generates all of Z_N* iff g^q == N-1.
        // RFC 5054 picks 5 for this group precisely because 2 does not.
        let n = n();
        let q = (&n - BigUint::from(1u32)) / BigUint::from(2u32);
        let g = BigUint::from(SRP_G);
        assert_eq!(g.modpow(&q, &n), &n - BigUint::from(1u32));
        assert_eq!(BigUint::from(2u32).modpow(&q, &n), BigUint::from(1u32));
    }

    /// Re-derives N from RFC 3526's published formula, so a typo in the literal
    /// cannot survive CI. This is the test that would have caught the original
    /// fabricated constant.
    #[test]
    fn srp_group_matches_rfc3526_formula() {
        // N = 2^3072 - 2^3008 - 1 + 2^64 * ( floor(2^2942 * pi) + 1690314 )
        //
        // floor(2^2942 * pi) is a fixed integer; rather than compute pi to 900
        // digits here, we check the equivalent rearrangement:
        //     (N - 2^3072 + 2^3008 + 1) / 2^64  -  1690314  ==  floor(2^2942 * pi)
        // and verify that value against pi's defining property, that it lies
        // strictly between the bounds given by a known convergent.
        let n = n();
        let two = BigUint::from(2u32);
        // Ordered to stay non-negative throughout: BigUint cannot hold an
        // intermediate below zero, and N < 2^3072.
        let numerator = (&n + two.pow(3008) + BigUint::from(1u32)) - two.pow(3072);
        assert_eq!(
            &numerator % two.pow(64),
            BigUint::from(0u32),
            "formula requires the 2^64 factor to divide exactly"
        );
        let term = numerator / two.pow(64) - BigUint::from(1690314u32);

        // floor(2^2942 * pi) must satisfy: term / 2^2942 is pi to 2942 bits.
        // Bound it with the classic convergent 355/113 < pi < 22/7 scaled up,
        // then tighten with a high-precision rational bound on pi.
        // pi > 3.14159265358979323846 and pi < 3.14159265358979323847
        let scale = two.pow(2942);
        let lo = (&scale * BigUint::from(314159265358979323846u128)) / BigUint::from(10u32).pow(20);
        let hi = (&scale * BigUint::from(314159265358979323847u128)) / BigUint::from(10u32).pow(20)
            + BigUint::from(1u32);
        assert!(term > lo, "derived pi term is too small");
        assert!(term < hi, "derived pi term is too large");
    }

    /// An independent implementation of the SRP-6a *server* side, used to check
    /// that the client agrees with something other than itself.
    struct RefServer {
        n: BigUint,
        g: BigUint,
        salt: Vec<u8>,
        v: BigUint,
        b: BigUint,
        big_b: BigUint,
    }

    impl RefServer {
        fn new(username: &str, password: &str, salt: &[u8], b: BigUint) -> Self {
            let n = group_n();
            let g = BigUint::from(SRP_G);

            // x = H(s | H(I | ":" | P)); v = g^x
            let inner = {
                let mut h = Sha512::new();
                h.update(username.as_bytes());
                h.update(b":");
                h.update(password.as_bytes());
                h.finalize()
            };
            let x = {
                let mut h = Sha512::new();
                h.update(salt);
                h.update(inner);
                BigUint::from_bytes_be(&h.finalize())
            };
            let v = g.modpow(&x, &n);

            // k = H(N | PAD(g)); B = (k*v + g^b) mod N
            let k = {
                let mut h = Sha512::new();
                h.update(n.to_bytes_be());
                h.update(pad_to_n(&g, &n));
                BigUint::from_bytes_be(&h.finalize())
            };
            let big_b = (&k * &v + g.modpow(&b, &n)) % &n;

            Self {
                n,
                g,
                salt: salt.to_vec(),
                v,
                b,
                big_b,
            }
        }

        /// Server-side K and the proofs it expects/sends.
        fn finish(&self, username: &str, a_padded: &[u8]) -> (Vec<u8>, Vec<u8>) {
            let big_a = BigUint::from_bytes_be(a_padded);
            let b_padded = pad_to_n(&self.big_b, &self.n);

            let u = {
                let mut h = Sha512::new();
                h.update(a_padded);
                h.update(&b_padded);
                BigUint::from_bytes_be(&h.finalize())
            };

            // S = (A * v^u)^b mod N
            let s = ((&big_a * self.v.modpow(&u, &self.n)) % &self.n).modpow(&self.b, &self.n);
            let key = {
                let mut h = Sha512::new();
                h.update(pad_to_n(&s, &self.n));
                h.finalize().to_vec()
            };

            let m1 = {
                let hash_n = Sha512::digest(self.n.to_bytes_be());
                let hash_g = Sha512::digest(self.g.to_bytes_be());
                let xor: Vec<u8> = hash_n
                    .iter()
                    .zip(hash_g.iter())
                    .map(|(l, r)| l ^ r)
                    .collect();
                let mut h = Sha512::new();
                h.update(&xor);
                h.update(Sha512::digest(username.as_bytes()));
                h.update(&self.salt);
                h.update(a_padded);
                h.update(&b_padded);
                h.update(&key);
                h.finalize().to_vec()
            };

            let m2 = {
                let mut h = Sha512::new();
                h.update(a_padded);
                h.update(&m1);
                h.update(&key);
                h.finalize().to_vec()
            };

            (m1, m2)
        }
    }

    #[test]
    fn client_and_reference_server_agree() {
        let username = "Pair-Setup";
        let password = "3939";
        let salt = [0x11u8; 16];
        let b = BigUint::from_bytes_be(&[0x42u8; 32]);

        let server = RefServer::new(username, password, &salt, b);
        let server_b = pad_to_n(&server.big_b, &group_n());

        let a = BigUint::from_bytes_be(&[0x37u8; 32]);
        let client = client_compute(username, password, &salt, &server_b, &a).unwrap();

        let (server_m1, server_m2) = server.finish(username, &client.public_a);

        assert_eq!(
            client.m1, server_m1,
            "client M1 must match what the server computes, or the server rejects M3"
        );
        assert_eq!(
            client.expected_m2, server_m2,
            "client must accept the M2 the server actually sends"
        );
    }

    /// Cross-implementation known-answer vector.
    ///
    /// # Where these numbers come from
    ///
    /// Generated with **srptools 1.0.1**, which is the SRP engine pyatv drives
    /// HAP pair-setup with — `pyatv/auth/hap_srp.py:140` constructs it as
    ///
    /// ```python
    /// SRPContext("Pair-Setup", str(pin), prime=constants.PRIME_3072,
    ///            generator=constants.PRIME_3072_GEN, hash_func=hashlib.sha512)
    /// ```
    ///
    /// and the vector below was produced with exactly that configuration,
    /// `I = "Pair-Setup"`, `P = "3939"`, `s = 0x11 * 16`, `a = 0x30 * 32`,
    /// `b = 0x40 * 32`, using **srptools' own `PRIME_3072`**, not ours.
    ///
    /// That last point is the whole value of this test.
    /// `client_and_reference_server_agree` above runs our client against a
    /// server written in this file: both halves share [`SRP_N_HEX`], so they
    /// agree on a wrong group exactly as happily as a right one — the
    /// self-consistency trap that let a fabricated, composite `N` ship. Here
    /// `A`, `K`, `M1` and `M2` were computed under a modulus this repository
    /// never supplied, so they only reproduce if our `N`, our generator, our
    /// hash composition, and our `PAD()` rules all match a third party's.
    ///
    /// # Encoding caveat
    ///
    /// srptools serialises integers with their minimal big-endian encoding
    /// (`srptools/utils.py::int_to_bytes`) where RFC 5054's `PAD()` left-pads
    /// to `len(N)`; the two coincide only for values with no leading zero byte.
    /// `a` and `b` were chosen so `A`, `B` and `S` are all exactly 384 bytes and
    /// the salt exactly 16, so the vector is not encoding-dependent. Anything
    /// that needs padding to differ — `u = H(PAD(A) | PAD(B))` — is still
    /// exercised, because srptools pads there too.
    #[test]
    fn matches_an_srptools_known_answer_vector() {
        // B, as srptools' server computes it: B = (k*v + g^b) mod N.
        const B_HEX: &str = "\
            22406281fc7bd58511cfb9372cb51c424d4a3bddf6f76020b387b14fe2b05afb\
            894c1e7d2fd851790d74b8ca58f06a88a02cf655060db2edb4516d3fd4e1c23b\
            3440609b793895564839b9443f2937e51bfccbe0a56112cd9f67ed9f557b4404\
            98df9ba204fe3a1abf6194468fbf5aadb10345adf9bf14a38c62eb878cc20015\
            a6760d5482eabe66c579d0e3fdcc90d63e79e4087a37b38cd4a5734e386fee85\
            921b3a17bd37a79ca1e564297661cf0c311b709c99a6a5f2048b10427a583dcb\
            4a4c71e92d6fa2bf4f6ff492388030239298488bcb9ca6e4d8f0e5f6d78b4031\
            96d29d6bf6f01b02a0472063b4cc20bb6000498d7fede6dc0671e92e6a79885d\
            285755cbbd90bea08d10da1d3a23c02087fc81981996521261384c63dc08a3b2\
            582f98f2d546e4c306656325d0fdb1fd54d008e3101d611fbdcb85caaa1dddb9\
            e17304fc81f0070fc96c0dff7fd41f32364d471d894936feb7cf99662ef2d572\
            fd3a4a41264f1f9e04c8f85b4651fce762200360dc90486e2ff5cb5b13667646";
        // A = g^a mod N. Depends on every bit of N.
        const A_HEX: &str = "\
            f1de45b315e35d81306e723b241b0050ac5edd8125eeb647e1f92d9b912f152f\
            ec7eedc9e8727075d20ca8912643cce335bab9404c130a807be98dbf2cc9d5f7\
            e0fc1801ed222bf9c2e3c072aeaeeab3b67db6016e913ade78e303659d55986e\
            387b5267b52c94dbffa12815d54e62bbec01f252d8c3d5e52e9c994dd93b996d\
            6c83ab83f61898703c1d6e8b5c4701f8c3a50b172c76b6b71e2a0e74757f8f93\
            df9889dfcd51fd976e69abbc4d5ef288900f9fbb1ee88f15d183d3eb6aa0f84e\
            7e4e62f1fc0f8991e6eca6c5a6427ccb7d352a2f09166e7ee528bfd5c8f2c330\
            571ef0d3e4bcd4d70899a9f4ab3e5f99c9dd6bdadb00648efd3b4c5c06ce61b1\
            ef348ed218f9c180356bcfc943310ea3c464f994d189152b65534c09ba83984d\
            d4754f4c6fcf3a9a7c0670f1dcc9d936e97164d1d23f4c82a2da56732aace97d\
            85d0fa876d79f419b740e489b23bf5c46f6a954e418585ea93dbd20c44a0e67f\
            a3bc1a968ac4ea9d3c3f8b572fccabc1cbc287ecdf07e6c9bad1804548e64b6b";
        // K = H(S), the key every later HKDF derivation hangs off.
        const K_HEX: &str = "\
            4b9fd27ccb3cf819622dc6579658cc4d73e77e7f65d8c65e98cf4ddae4fe98ea\
            ee3edb3bbcd2f6ec1817035a0a13f827bd6b4d3c19df5474a24527668aa13cc6";
        // M1 = H(H(N) XOR H(g) | H(I) | s | A | B | K), the proof sent in M3.
        const M1_HEX: &str = "\
            68bfb13622e54efc5a3cc6663af00a292d3d5e4024d86d9c8dc261f7ece945c2\
            8374df1abd6555502de39ea5acb00580f8f8b0743e72ee4bcc69b951f1b94679";
        // M2 = H(A | M1 | K), the proof the accessory returns in M4.
        const M2_HEX: &str = "\
            99ab3d6381f24e123605781cd8169af9e5b6a2c1bd85c81d66467844840ee38d\
            0770f94ba76d36c5ae206f01a53174f329a44b796fa837b8e5d94dddb9b40032";

        let salt = [0x11u8; 16];
        let a = BigUint::from_bytes_be(&[0x30u8; 32]);

        let client = client_compute("Pair-Setup", "3939", &salt, &unhex(B_HEX), &a).unwrap();

        assert_eq!(
            client.public_a,
            unhex(A_HEX),
            "A disagrees with srptools — the group modulus or the generator differs"
        );
        assert_eq!(
            client.session_key,
            unhex(K_HEX),
            "K disagrees — x, u, k, S or the encoding of S differs"
        );
        assert_eq!(
            client.m1,
            unhex(M1_HEX),
            "M1 disagrees — the accessory would reject M3"
        );
        assert_eq!(
            client.expected_m2,
            unhex(M2_HEX),
            "M2 disagrees — we would reject the accessory's M4"
        );
    }

    /// Hex to bytes, ignoring the layout whitespace in the constants above.
    fn unhex(s: &str) -> Vec<u8> {
        let digits: Vec<u8> = s.bytes().filter(|b| !b.is_ascii_whitespace()).collect();
        assert_eq!(digits.len() % 2, 0, "hex constant has an odd digit count");
        digits
            .chunks(2)
            .map(|pair| {
                u8::from_str_radix(std::str::from_utf8(pair).unwrap(), 16)
                    .expect("hex constant contains a non-hex digit")
            })
            .collect()
    }

    #[test]
    fn wrong_pin_produces_a_different_proof() {
        let username = "Pair-Setup";
        let salt = [0x11u8; 16];
        let b = BigUint::from_bytes_be(&[0x42u8; 32]);

        let server = RefServer::new(username, "3939", &salt, b);
        let server_b = pad_to_n(&server.big_b, &group_n());

        let a = BigUint::from_bytes_be(&[0x37u8; 32]);
        let client = client_compute(username, "0000", &salt, &server_b, &a).unwrap();
        let (server_m1, _) = server.finish(username, &client.public_a);

        assert_ne!(client.m1, server_m1, "a wrong PIN must not verify");
    }

    #[test]
    fn rejects_b_congruent_to_zero() {
        let n = group_n();
        let zero_b = pad_to_n(&n, &n); // B == N, so B mod N == 0
        let a = BigUint::from_bytes_be(&[0x37u8; 32]);
        // Matched rather than unwrap_err()'d: ClientSession deliberately does not
        // derive Debug, since it holds the session key K.
        let err = match client_compute("Pair-Setup", "3939", &[0u8; 16], &zero_b, &a) {
            Ok(_) => panic!("B congruent to 0 mod N must be rejected"),
            Err(e) => e,
        };
        assert!(err.to_string().contains("congruent to 0"), "got: {err}");
    }

    #[test]
    fn public_a_is_padded_to_the_group_length() {
        let a = BigUint::from_bytes_be(&[0x37u8; 32]);
        let server = RefServer::new("Pair-Setup", "3939", &[0u8; 16], BigUint::from(3u32));
        let server_b = pad_to_n(&server.big_b, &group_n());
        let client = client_compute("Pair-Setup", "3939", &[0u8; 16], &server_b, &a).unwrap();
        assert_eq!(client.public_a.len(), 384, "A must be PAD()ed to 384 bytes");
    }
}
